name: Russ Vann
favicon: null
layout_spectrum: 0.6995997205376625
typography_spectrum: 0.51754
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.5619051477406174
  lightness: 0.8715224119368941
  saturation: 0.4598284028470516
  rhythmicContrast: 0.5997931561432779
purpose: []
